steps:
  - name: node
    entrypoint: npm
    args: ['ci']
  - name: node
    entrypoint: npm
    args: ['run', 'cloud-secrets']
    env:
    - 'PROJECT_ID=$PROJECT_ID'
  - name: 'gcr.io/web-dev-production-1/firebase'
    args: ['deploy', '--project=web-dev-production-1']
timeout: 1200s
